### ISSUE TITLE
Text Overlap, Rectangle Sizing and Rectangle Blue Fill

### ISSUE THREAD

**Issue by mark-knox** [manikmagar/mulefd#256] opened 2022-06-24 16:46 UTC
1. When a sub-flow graphic is generated, the word **sub-flow** overlaps the description.  See attached screenshot.
2. When rendering a rectangle for a flow, the flow description will sometimes exceed the length of the rectangle and be printed outside the right-hand border.  See attached screenshot.
3. One of the diagrams I generated had a rectangle with a solid blue fill.  Not sure what that means.  See attached screenshot.
![Screen Shot 2022-06-24 at 11 19 12 AM](https://user-images.githubusercontent.com/88405514/175604395-1307fc45-c9ac-421c-b3fb-e42918af8761.png)
![Screen Shot 2022-06-24 at 11 36 52 AM](https://user-images.githubusercontent.com/88405514/175604430-56520cca-1e9d-4f74-a66d-f405864c0504.png)
![Screen Shot 2022-06-24 at 12 03 52 PM](https://user-images.githubusercontent.com/88405514/175609501-552ba637-6d5c-4d7a-881f-7d45947f72dd.png)

**Comment by manikmagar** [comment] 2022-06-24 17:00
Thank you for trying and reporting this @mark-knox.

**Comment by mark-knox** [comment] 2022-06-24 17:10
@manikmagar happy to help!

**Comment by manikmagar** [comment] 2022-10-22 15:38
I think I know what is happening here. When the default fonts of Times and Serif are not available, the size of the label and required shape size aren't matching and thus labels going out of the shape.

Changing to default font to a more commonly available fonts, such as Arial works well. That one at least can be fixed in upcoming release.

Still cannot reproduce the behavior of blue filled box. Not sure why/when that could happen.

**Comment by manikmagar** [comment] 2022-10-24 00:21
PR #290 introduces config support to change the font used. The default font used hasn't changed. If text overlapping behavior is observed (most likely on Mac OS Monterey), then set the font name. See https://github.com/manikmagar/mulefd#configuration for property details.

**Comment by manikmagar** [comment] 2022-10-26 01:32
@mark-knox could you try with v0.9.0? If you still get overlapped text, I suggest changing the font used. Maybe set it to "Arial". See here for how to set that - https://github.com/manikmagar/mulefd#configuration

**Comment by manikmagar** [comment] 2022-10-27 02:15
I found the cause of blue filled flow rectangle. This happens for an APIKIT generated flow that does not reference any other flow. Unused flow look up is unable to find the link between APIKIT router and referenced flow in that case.


![image](https://user-images.githubusercontent.com/877286/198174846-f0eaa0ee-defb-4731-8b28-ea238262c3af.png)

**Closed** 2022-10-29 17:32 UTC
Labels: bug
